### PR TITLE
Update some dependencies

### PR DESCRIPTION
**Pull request by Muzammal01**
I update some packages like filament and also update some dependencies

### CODE REVIEW

**Comment by Muzammal01** [comment]
I tested it on my computer and it worked perfectly. Please also check it on your computer before adding it to the main branch.

**Comment by Muzammal01** [comment]
I tested it on my computer and it worked perfectly. Please also check it on your computer before adding it to the main branch.

**Comment by Muzammal01** [comment]
I tested it on my computer and it worked perfectly. Please also check it on your computer before adding it to the main branch.

**Comment by phi-rakib** [comment]
Hi @Muzammal01,

Thank you for your contribution to the project and for taking the time to update the packages. I appreciate your effort in helping to keep the repository up to date. However, I prefer to handle package updates myself to ensure compatibility with the existing codebase and to manage any potential issues that may arise during the update process.

For this reason, I will be closing this pull request. Please feel free to contribute to other areas of the project, and don't hesitate to reach out if you have any other suggestions or ideas.

Thank you for understanding.

Best regards,
Mohammad Rakibul Haider

**Pull request closed without merging**
